name: CI

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload to IPFS
        id: upload
        uses: aquiladev/ipfs-action@v0.1.2-alpha
        with:
          path: ./build

      - name: Update ENS
        uses: aquiladev/ddns-action@v0.1.1
        with:
          mnemonic: ${{ secrets.MNEMONIC }}
          rpc: ${{ secrets.RPC }}
          name: ddns-action.eth
          contentHash: ${{ steps.upload.outputs.hash }}
