name: CI

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Consiglio di usare una versione LTS stabile

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn next:build

      - name: List files after build
        run: ls -la

      - name: Upload to IPFS
        id: upload
        uses: aquiladev/ipfs-action@master
        with:
            path: ./out  
            service: infura
            infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
            infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: Update ENS
        uses: aquiladev/ddns-action@v0.1.1
        with:
          mnemonic: ${{ secrets.MNEMONIC }}
          rpc: ${{ secrets.RPC }}
          name: ddns-action.eth
          contentHash: ${{ steps.upload.outputs.hash }}